### ISSUE TITLE
Extra users (user1, user2, user5, user6) also created

### ISSUE THREAD

**Issue by mendhak** [duxklr/manageusers#1]
Thanks for making this module.

When I ran it and tried to create a user, this module did create the user, but also created a bunch of extras.  My /etc/passwd now shows these guys:

```
user2:x:701:701:Jane Smith:/home/user2:/bin/bash
user6:x:706:706:Bob Smith:/home/user6:/bin/bash
user1:x:700:700:John Smith:/home/user1:/bin/bash
user5:x:703:703:John Doe:/home/user5:/bin/bash
```

Running Ubuntu 14.04 x64, Puppet 3.4.3 on a fresh VM.

I used this:

```
manageusers::create_account { "myuser":
    name       => "My User",
    uid        => "1001",
    password   => '$1$2wsBH/P7....',
    shell      => "/bin/bash",
    groups     => ['sudo', 'myuser'],
    sshkeytype => "ssh-rsa",
    sshkey     => "AAAAB3NzaC1yc2EAAAADAQABAA....",
}
```

When I attempt to remove these users,

```
user { 'user1': ensure=> 'absent',}
```

I get

```
User[user1] is already declared in file /etc/puppet/manifests/site.pp:123; cannot redeclare at /etc/puppet/modules/manageusers/manifests/create_account.pp:22 on node cloudserver.home
```

**Comment by 0xJasonMurray** [comment]
The .../manifests/add_accounts.pp and .../manifests/remove_accounts.pp have example entires in them that should be removed before you run the module.

Do you feel that the example accounts should be commented out by default?

**Comment by mendhak** [comment]
OK, removing lines from there works, all clean now.

I think ideally, as it's a module, it wouldn't create extra users since modules are meant to be reusable/standalone.  For example, `file` doesn't create test files.  

Instead the stuff in add_accounts and remove_accounts could be very useful as part of the readme examples!

**Comment by 0xJasonMurray** [comment]
Good point.   Example accounts have been removed.   Version 0.0.6 has been pushed to Puppet Forge and GitHub has been updated.

Thanks for the feedback.

**Comment by swapnil-jaiswal** [comment]
Hi,
If i need to create a user a/c on 2 machines in my server stack (NOT all machines)
How should i use the or condition ?

Following Example did not work ;
Please suggest a correct approach ?

  if ($fqdn == "ip-xxx-xx-20-125.ap-southeast-1.compute.internal")  or  ($fqdn == "ip-xxx-xx-24-200.ap-southeast-1.compute.internal")    {		## Middleware ##  ### java ##
   manageusers::create_account { "hello.world" :
    name       => "hello.world",
    uid        => "701",
    password   => '$1$abcedfghijkl12345mnopqrstuvwxyz',
    shell      => "/bin/bash",
    groups     => ['hello.world', 'hello.world'],
    sshkeytype => "ssh-rsa",
    sshkey     => "AAAAB3NzaC1yc2EAAAADAQABAAABAQDPfg67NAK7Wap9nnRQZ/VhxY/DXmQqXdaR+BSHMcIssfrt7W+Qm6vidOtb+MFQQ/Xf+eunVoJz0alSzQ7"
  }
}
