### ISSUE TITLE
Password not working

### ISSUE THREAD

**Issue by sgtstadanko** [duxklr/manageusers#2]
Hey,

Love the module. However I dont seem to be able to login with any password that I set in add_accounts.pp.  I have tried the same one provided in the example and just some other random passwords.  

Thanks,
Bill

**Comment by 0xJasonMurray** [comment]
What format are you putting your password in?   It needs to be one of the OS supported encrypted formats such as SHA or MD5.

**Comment by 0xJasonMurray** [comment]
No update, closing issue.
